name: orix
description: "ORIX - College Ride Coordination Platform"
publish_to: 'none'

version: 2.0.2+5

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  firebase_messaging: ^16.1.0
  google_sign_in: ^7.2.0
  
  # State Management
  provider: ^6.1.5
  
  # Navigation
  go_router: ^17.0.1
  # Networking
  http: ^1.3.0
  web_socket_channel: ^3.0.3
  http_parser: ^4.1.2
  
  # Maps
  flutter_map: ^8.2.2
  flutter_map_cancellable_tile_provider: ^3.1.1
  latlong2: ^0.9.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  
  # Storage
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^10.0.0
  
  # UI
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_svg: ^2.2.3
  
  # Utils
  intl: ^0.20.2
  url_launcher: ^6.3.2
  permission_handler: ^12.0.1
  connectivity_plus: ^7.0.0
  firebase_analytics: ^12.1.0
  image_picker: ^1.2.1
  firebase_storage: ^13.0.5
  package_info_plus: 8.3.1
  google_mobile_ads: ^7.0.0
  flutter_local_notifications: ^19.5.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.6
  build_runner: ^2.4.15

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/Orix_Logo.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/images/
    - assets/icons/
  
  # Uncomment after adding Outfit font files to assets/fonts/
  # Download from: https://fonts.google.com/specimen/Outfit
  # fonts:
  #   - family: Outfit
  #     fonts:
  #       - asset: assets/fonts/Outfit-Regular.ttf
  #       - asset: assets/fonts/Outfit-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Outfit-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Outfit-Bold.ttf
  #         weight: 700
